services:
  postgres:
    image: postgres:16
    container_name: grantflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: grantflow_db
      POSTGRES_USER: grantflow_user
      POSTGRES_PASSWORD: grantflow_password

    ports:
      - "5432:5432"

    volumes:
      - grantflow_postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  grantflow_postgres_data: